id: IADCDDD64
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T15:30:18+00:00'
last_modified: '2022-06-07T22:32:31.227576+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29991
  title: དུས་སྐབས་གསར་པའི་བོད་ཀྱི་སྒྲུང་གཏམ་ལ་དཔྱད་པ་བློ་གསར་དགྱེས་པའི་དགའ་སྟོན། ༼༡༩༧༨-༢༠༠༠༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    2D2C:
      image_group_id: I1KG12941
      title: ''
      total_pages: 274
      order: 1
      base_file: 2D2C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
