id: P004392
initial_creation_type: ocr
source_metadata:
  id: bdr:W29991
  title: དུས་སྐབས་གསར་པའི་བོད་ཀྱི་སྒྲུང་གཏམ་ལ་དཔྱད་པ་བློ་གསར་དགྱེས་པའི་དགའ་སྟོན། ༼༡༩༧༨-༢༠༠༠༽
  author: ''
  volumes:
    ff1d9bc4a181434681164e935c65f84f:
      image_group_id: I1KG12941
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
